# Base24 Ultra Violet
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Tinted Theming: (https://github.com/tinted-theming)

# Global base24 color variables
%hidden base00="#242728"
%hidden base01="#232628"
%hidden base02="#626566"
%hidden base03="#818484"
%hidden base04="#a1a3a3"
%hidden base05="#c1c2c2"
%hidden base06="#e1e1e1"
%hidden base07="#f9f9f4"
%hidden base08="#ff0090"
%hidden base09="#fff727"
%hidden base0A="#7febff"
%hidden base0B="#b5ff00"
%hidden base0C="#0effbb"
%hidden base0D="#47dffb"
%hidden base0E="#d630ff"
%hidden base10="#414344"
%hidden base11="#202122"
%hidden base12="#fb57b4"
%hidden base13="#ebdf86"
%hidden base14="#deff8b"
%hidden base15="#68fcd2"
%hidden base16="#7febff"
%hidden base17="#e681ff"

# default statusbar colors
set-option -g status-style "fg=#a1a3a3,bg=#232628"

# default window title colors
set-window-option -g window-status-style "fg=#a1a3a3,bg=#232628"

# active window title colors
set-window-option -g window-status-current-style "fg=#ebdf86,bg=#232628"

# pane border
set-option -g pane-border-style "fg=#232628"
set-option -g pane-active-border-style "fg=#a1a3a3"

# message text
set-option -g message-style "fg=#e1e1e1,bg=#626566"

# pane number display
set-option -g display-panes-active-colour "#a1a3a3"
set-option -g display-panes-colour "#232628"

# clock
set-window-option -g clock-mode-colour "#47dffb"

# copy mode highlight
set-window-option -g mode-style "fg=#a1a3a3,bg=#626566"

# bell
set-window-option -g window-status-bell-style "fg=#242728,bg=#ff0090"

# style for window titles with activity
set-window-option -g window-status-activity-style "fg=#c1c2c2,bg=#232628"

# style for command messages
set-option -g message-command-style "fg=#e1e1e1,bg=#626566"

# Optional active/inactive pane state
if-shell '[ "$TINTED_TMUX_OPTION_ACTIVE" = "1" ]' {
  set-window-option -g window-active-style "fg=#c1c2c2,bg=#242728"
  set-window-option -g window-style "fg=#c1c2c2,bg=#232628"
}

# Optional statusbar
if-shell '[ "$TINTED_TMUX_OPTION_STATUSBAR" = "1" ]' {
  set-option -g status "on"
  set-option -g status-justify "left"
  set-option -g status-left "#[fg=#c1c2c2,bg=#818484] #S #[fg=#818484,bg=#232628,nobold,noitalics,nounderscore]"
  set-option -g status-left-length "80"
  set-option -g status-left-style none
  set-option -g status-right "#[fg=#626566,bg=#232628 nobold, nounderscore, noitalics]#[fg=#a1a3a3,bg=#626566] %Y-%m-%d  %H:%M #[fg=#c1c2c2,bg=#626566,nobold,noitalics,nounderscore]#[fg=#232628,bg=#c1c2c2] #h "
  set-option -g status-right-length "80"
  set-option -g status-right-style none
  set-window-option -g window-status-current-format "#[fg=#232628,bg=#7febff,nobold,noitalics,nounderscore]#[fg=#626566,bg=#7febff] #I #[fg=#626566,bg=#7febff,bold] #W#{?window_zoomed_flag,*Z,}} #[fg=#7febff,bg=#232628,nobold,noitalics,nounderscore]"
  set-window-option -g window-status-format "#[fg=#232628,bg=#626566,noitalics]#[fg=#e1e1e1,bg=#626566] #I #[fg=#e1e1e1,bg=#626566] #W#{?window_zoomed_flag,*Z,}} #[fg=#626566,bg=#232628,noitalics]"
  set-window-option -g window-status-separator ""
}

# vim: set ft=tmux tw=0:
