# Base16 lime
# Scheme author: limelier
# Template author: Tinted Theming: (https://github.com/tinted-theming)

# Global base16 color variables
%hidden base00="#1a1a2f"
%hidden base01="#202030"
%hidden base02="#2a2a3f"
%hidden base03="#313140"
%hidden base04="#515155"
%hidden base05="#818175"
%hidden base06="#fff2d1"
%hidden base07="#fff8e1"
%hidden base08="#ff662a"
%hidden base09="#ff773a"
%hidden base0A="#ffd15e"
%hidden base0B="#8cd97c"
%hidden base0C="#4cad83"
%hidden base0D="#2b926f"
%hidden base0E="#1b825f"
%hidden base0F="#b4d97c"

# default statusbar colors
set-option -g status-style "fg=#515155,bg=#202030"

# default window title colors
set-window-option -g window-status-style "fg=#515155,bg=#202030"

# active window title colors
set-window-option -g window-status-current-style "fg=#ffd15e,bg=#202030"

# pane border
set-option -g pane-border-style "fg=#202030"
set-option -g pane-active-border-style "fg=#515155"

# message text
set-option -g message-style "fg=#fff2d1,bg=#2a2a3f"

# pane number display
set-option -g display-panes-active-colour "#515155"
set-option -g display-panes-colour "#202030"

# clock
set-window-option -g clock-mode-colour "#2b926f"

# copy mode highlight
set-window-option -g mode-style "fg=#515155,bg=#2a2a3f"

# bell
set-window-option -g window-status-bell-style "fg=#1a1a2f,bg=#ff662a"

# style for window titles with activity
set-window-option -g window-status-activity-style "fg=#818175,bg=#202030"

# style for command messages
set-option -g message-command-style "fg=#fff2d1,bg=#2a2a3f"

# Optional active/inactive pane state
# BASE16_TMUX_OPTION_ACTIVE is a legacy variable
if-shell '[ "$TINTED_TMUX_OPTION_ACTIVE" = "1" ] || [ "$BASE16_TMUX_OPTION_ACTIVE" = "1" ]' {
  set-window-option -g window-active-style "fg=#818175,bg=#1a1a2f"
  set-window-option -g window-style "fg=#818175,bg=#202030"
}

# Optional statusbar
# BASE16_TMUX_OPTION_STATUSBAR is a legacy variable
if-shell '[ "$TINTED_TMUX_OPTION_STATUSBAR" = "1" ] || [ "$BASE16_TMUX_OPTION_STATUSBAR" = "1" ]' {
  set-option -g status "on"
  set-option -g status-justify "left"
  set-option -g status-left "#[fg=#818175,bg=#313140] #S #[fg=#313140,bg=#202030,nobold,noitalics,nounderscore]"
  set-option -g status-left-length "80"
  set-option -g status-left-style none
  set-option -g status-right "#[fg=#2a2a3f,bg=#202030 nobold, nounderscore, noitalics]#[fg=#515155,bg=#2a2a3f] %Y-%m-%d  %H:%M #[fg=#818175,bg=#2a2a3f,nobold,noitalics,nounderscore]#[fg=#202030,bg=#818175] #h "
  set-option -g status-right-length "80"
  set-option -g status-right-style none
  set-window-option -g window-status-current-format "#[fg=#202030,bg=#ffd15e,nobold,noitalics,nounderscore]#[fg=#2a2a3f,bg=#ffd15e] #I #[fg=#2a2a3f,bg=#ffd15e,bold] #W#{?window_zoomed_flag,*Z,} #[fg=#ffd15e,bg=#202030,nobold,noitalics,nounderscore]"
  set-window-option -g window-status-format "#[fg=#202030,bg=#2a2a3f,noitalics]#[fg=#fff2d1,bg=#2a2a3f] #I #[fg=#fff2d1,bg=#2a2a3f] #W#{?window_zoomed_flag,*Z,} #[fg=#2a2a3f,bg=#202030,noitalics]"
  set-window-option -g window-status-separator ""
}

# vim: set ft=tmux tw=0:
