# Base24 Spiderman
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Tinted Theming: (https://github.com/tinted-theming)

# Global base24 color variables
%hidden base00="#1b1d1e"
%hidden base01="#1b1d1e"
%hidden base02="#505354"
%hidden base03="#7b7d7c"
%hidden base04="#a7a8a5"
%hidden base05="#d3d3cd"
%hidden base06="#fffef6"
%hidden base07="#fefff9"
%hidden base08="#e60712"
%hidden base09="#e24655"
%hidden base0A="#1d4fff"
%hidden base0B="#e22828"
%hidden base0C="#3255ff"
%hidden base0D="#2b3fff"
%hidden base0E="#2435db"
%hidden base10="#353738"
%hidden base11="#1a1b1c"
%hidden base12="#ff0325"
%hidden base13="#fe3935"
%hidden base14="#ff3238"
%hidden base15="#6083ff"
%hidden base16="#1d4fff"
%hidden base17="#737bff"

# default statusbar colors
set-option -g status-style "fg=#a7a8a5,bg=#1b1d1e"

# default window title colors
set-window-option -g window-status-style "fg=#a7a8a5,bg=#1b1d1e"

# active window title colors
set-window-option -g window-status-current-style "fg=#fe3935,bg=#1b1d1e"

# pane border
set-option -g pane-border-style "fg=#1b1d1e"
set-option -g pane-active-border-style "fg=#a7a8a5"

# message text
set-option -g message-style "fg=#fffef6,bg=#505354"

# pane number display
set-option -g display-panes-active-colour "#a7a8a5"
set-option -g display-panes-colour "#1b1d1e"

# clock
set-window-option -g clock-mode-colour "#2b3fff"

# copy mode highlight
set-window-option -g mode-style "fg=#a7a8a5,bg=#505354"

# bell
set-window-option -g window-status-bell-style "fg=#1b1d1e,bg=#e60712"

# style for window titles with activity
set-window-option -g window-status-activity-style "fg=#d3d3cd,bg=#1b1d1e"

# style for command messages
set-option -g message-command-style "fg=#fffef6,bg=#505354"

# Optional active/inactive pane state
if-shell '[ "$TINTED_TMUX_OPTION_ACTIVE" = "1" ]' {
  set-window-option -g window-active-style "fg=#d3d3cd,bg=#1b1d1e"
  set-window-option -g window-style "fg=#d3d3cd,bg=#1b1d1e"
}

# Optional statusbar
if-shell '[ "$TINTED_TMUX_OPTION_STATUSBAR" = "1" ]' {
  set-option -g status "on"
  set-option -g status-justify "left"
  set-option -g status-left "#[fg=#d3d3cd,bg=#7b7d7c] #S #[fg=#7b7d7c,bg=#1b1d1e,nobold,noitalics,nounderscore]"
  set-option -g status-left-length "80"
  set-option -g status-left-style none
  set-option -g status-right "#[fg=#505354,bg=#1b1d1e nobold, nounderscore, noitalics]#[fg=#a7a8a5,bg=#505354] %Y-%m-%d  %H:%M #[fg=#d3d3cd,bg=#505354,nobold,noitalics,nounderscore]#[fg=#1b1d1e,bg=#d3d3cd] #h "
  set-option -g status-right-length "80"
  set-option -g status-right-style none
  set-window-option -g window-status-current-format "#[fg=#1b1d1e,bg=#1d4fff,nobold,noitalics,nounderscore]#[fg=#505354,bg=#1d4fff] #I #[fg=#505354,bg=#1d4fff,bold] #W#{?window_zoomed_flag,*Z,}} #[fg=#1d4fff,bg=#1b1d1e,nobold,noitalics,nounderscore]"
  set-window-option -g window-status-format "#[fg=#1b1d1e,bg=#505354,noitalics]#[fg=#fffef6,bg=#505354] #I #[fg=#fffef6,bg=#505354] #W#{?window_zoomed_flag,*Z,}} #[fg=#505354,bg=#1b1d1e,noitalics]"
  set-window-option -g window-status-separator ""
}

# vim: set ft=tmux tw=0:
