# Base24 Under The Sea
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Tinted Theming: (https://github.com/tinted-theming)

# Global base24 color variables
%hidden base00="#001015"
%hidden base01="#022026"
%hidden base02="#374350"
%hidden base03="#394751"
%hidden base04="#3b4c52"
%hidden base05="#3d5053"
%hidden base06="#405554"
%hidden base07="#58fad6"
%hidden base08="#b12f2c"
%hidden base09="#58809c"
%hidden base0A="#61d4b9"
%hidden base0B="#00a940"
%hidden base0C="#5c7e19"
%hidden base0D="#449985"
%hidden base0E="#00599c"
%hidden base10="#242c35"
%hidden base11="#12161a"
%hidden base12="#ff4242"
%hidden base13="#8dd3fd"
%hidden base14="#2aea5e"
%hidden base15="#98cf28"
%hidden base16="#61d4b9"
%hidden base17="#1298ff"

# default statusbar colors
set-option -g status-style "fg=#3b4c52,bg=#022026"

# default window title colors
set-window-option -g window-status-style "fg=#3b4c52,bg=#022026"

# active window title colors
set-window-option -g window-status-current-style "fg=#8dd3fd,bg=#022026"

# pane border
set-option -g pane-border-style "fg=#022026"
set-option -g pane-active-border-style "fg=#3b4c52"

# message text
set-option -g message-style "fg=#405554,bg=#374350"

# pane number display
set-option -g display-panes-active-colour "#3b4c52"
set-option -g display-panes-colour "#022026"

# clock
set-window-option -g clock-mode-colour "#449985"

# copy mode highlight
set-window-option -g mode-style "fg=#3b4c52,bg=#374350"

# bell
set-window-option -g window-status-bell-style "fg=#001015,bg=#b12f2c"

# style for window titles with activity
set-window-option -g window-status-activity-style "fg=#3d5053,bg=#022026"

# style for command messages
set-option -g message-command-style "fg=#405554,bg=#374350"

# Optional active/inactive pane state
if-shell '[ "$TINTED_TMUX_OPTION_ACTIVE" = "1" ]' {
  set-window-option -g window-active-style "fg=#3d5053,bg=#001015"
  set-window-option -g window-style "fg=#3d5053,bg=#022026"
}

# Optional statusbar
if-shell '[ "$TINTED_TMUX_OPTION_STATUSBAR" = "1" ]' {
  set-option -g status "on"
  set-option -g status-justify "left"
  set-option -g status-left "#[fg=#3d5053,bg=#394751] #S #[fg=#394751,bg=#022026,nobold,noitalics,nounderscore]"
  set-option -g status-left-length "80"
  set-option -g status-left-style none
  set-option -g status-right "#[fg=#374350,bg=#022026 nobold, nounderscore, noitalics]#[fg=#3b4c52,bg=#374350] %Y-%m-%d  %H:%M #[fg=#3d5053,bg=#374350,nobold,noitalics,nounderscore]#[fg=#022026,bg=#3d5053] #h "
  set-option -g status-right-length "80"
  set-option -g status-right-style none
  set-window-option -g window-status-current-format "#[fg=#022026,bg=#61d4b9,nobold,noitalics,nounderscore]#[fg=#374350,bg=#61d4b9] #I #[fg=#374350,bg=#61d4b9,bold] #W#{?window_zoomed_flag,*Z,}} #[fg=#61d4b9,bg=#022026,nobold,noitalics,nounderscore]"
  set-window-option -g window-status-format "#[fg=#022026,bg=#374350,noitalics]#[fg=#405554,bg=#374350] #I #[fg=#405554,bg=#374350] #W#{?window_zoomed_flag,*Z,}} #[fg=#374350,bg=#022026,noitalics]"
  set-window-option -g window-status-separator ""
}

# vim: set ft=tmux tw=0:
