# Base24 Vibrant Ink
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Tinted Theming: (https://github.com/tinted-theming)

# Global base24 color variables
%hidden base00="#000000"
%hidden base01="#878787"
%hidden base02="#555555"
%hidden base03="#7d7d7d"
%hidden base04="#a5a5a5"
%hidden base05="#cdcdcd"
%hidden base06="#f5f5f5"
%hidden base07="#e5e5e5"
%hidden base08="#ff6600"
%hidden base09="#ffcc00"
%hidden base0A="#0000ff"
%hidden base0B="#ccff04"
%hidden base0C="#44b3cc"
%hidden base0D="#44b3cc"
%hidden base0E="#9933cc"
%hidden base10="#383838"
%hidden base11="#1c1c1c"
%hidden base12="#ff0000"
%hidden base13="#ffff00"
%hidden base14="#00ff00"
%hidden base15="#00ffff"
%hidden base16="#0000ff"
%hidden base17="#ff00ff"

# default statusbar colors
set-option -g status-style "fg=#a5a5a5,bg=#878787"

# default window title colors
set-window-option -g window-status-style "fg=#a5a5a5,bg=#878787"

# active window title colors
set-window-option -g window-status-current-style "fg=#ffff00,bg=#878787"

# pane border
set-option -g pane-border-style "fg=#878787"
set-option -g pane-active-border-style "fg=#a5a5a5"

# message text
set-option -g message-style "fg=#f5f5f5,bg=#555555"

# pane number display
set-option -g display-panes-active-colour "#a5a5a5"
set-option -g display-panes-colour "#878787"

# clock
set-window-option -g clock-mode-colour "#44b3cc"

# copy mode highlight
set-window-option -g mode-style "fg=#a5a5a5,bg=#555555"

# bell
set-window-option -g window-status-bell-style "fg=#000000,bg=#ff6600"

# style for window titles with activity
set-window-option -g window-status-activity-style "fg=#cdcdcd,bg=#878787"

# style for command messages
set-option -g message-command-style "fg=#f5f5f5,bg=#555555"

# Optional active/inactive pane state
if-shell '[ "$TINTED_TMUX_OPTION_ACTIVE" = "1" ]' {
  set-window-option -g window-active-style "fg=#cdcdcd,bg=#000000"
  set-window-option -g window-style "fg=#cdcdcd,bg=#878787"
}

# Optional statusbar
if-shell '[ "$TINTED_TMUX_OPTION_STATUSBAR" = "1" ]' {
  set-option -g status "on"
  set-option -g status-justify "left"
  set-option -g status-left "#[fg=#cdcdcd,bg=#7d7d7d] #S #[fg=#7d7d7d,bg=#878787,nobold,noitalics,nounderscore]"
  set-option -g status-left-length "80"
  set-option -g status-left-style none
  set-option -g status-right "#[fg=#555555,bg=#878787 nobold, nounderscore, noitalics]#[fg=#a5a5a5,bg=#555555] %Y-%m-%d  %H:%M #[fg=#cdcdcd,bg=#555555,nobold,noitalics,nounderscore]#[fg=#878787,bg=#cdcdcd] #h "
  set-option -g status-right-length "80"
  set-option -g status-right-style none
  set-window-option -g window-status-current-format "#[fg=#878787,bg=#0000ff,nobold,noitalics,nounderscore]#[fg=#555555,bg=#0000ff] #I #[fg=#555555,bg=#0000ff,bold] #W#{?window_zoomed_flag,*Z,}} #[fg=#0000ff,bg=#878787,nobold,noitalics,nounderscore]"
  set-window-option -g window-status-format "#[fg=#878787,bg=#555555,noitalics]#[fg=#f5f5f5,bg=#555555] #I #[fg=#f5f5f5,bg=#555555] #W#{?window_zoomed_flag,*Z,}} #[fg=#555555,bg=#878787,noitalics]"
  set-window-option -g window-status-separator ""
}

# vim: set ft=tmux tw=0:
