# Base24 Purplepeter
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Tinted Theming: (https://github.com/tinted-theming)

# Global base24 color variables
%hidden base00="#2a1a4a"
%hidden base01="#0a041f"
%hidden base02="#100b22"
%hidden base03="#4b3639"
%hidden base04="#876251"
%hidden base05="#c38e69"
%hidden base06="#ffba81"
%hidden base07="#b9aed3"
%hidden base08="#ff786c"
%hidden base09="#efdeab"
%hidden base0A="#79daed"
%hidden base0B="#98b481"
%hidden base0C="#b98cff"
%hidden base0D="#66d9ef"
%hidden base0E="#e68ecd"
%hidden base10="#0a0716"
%hidden base11="#05030b"
%hidden base12="#f89f92"
%hidden base13="#f1e9bf"
%hidden base14="#b4bd8e"
%hidden base15="#a0a0d6"
%hidden base16="#79daed"
%hidden base17="#b991d4"

# default statusbar colors
set-option -g status-style "fg=#876251,bg=#0a041f"

# default window title colors
set-window-option -g window-status-style "fg=#876251,bg=#0a041f"

# active window title colors
set-window-option -g window-status-current-style "fg=#f1e9bf,bg=#0a041f"

# pane border
set-option -g pane-border-style "fg=#0a041f"
set-option -g pane-active-border-style "fg=#876251"

# message text
set-option -g message-style "fg=#ffba81,bg=#100b22"

# pane number display
set-option -g display-panes-active-colour "#876251"
set-option -g display-panes-colour "#0a041f"

# clock
set-window-option -g clock-mode-colour "#66d9ef"

# copy mode highlight
set-window-option -g mode-style "fg=#876251,bg=#100b22"

# bell
set-window-option -g window-status-bell-style "fg=#2a1a4a,bg=#ff786c"

# style for window titles with activity
set-window-option -g window-status-activity-style "fg=#c38e69,bg=#0a041f"

# style for command messages
set-option -g message-command-style "fg=#ffba81,bg=#100b22"

# Optional active/inactive pane state
if-shell '[ "$TINTED_TMUX_OPTION_ACTIVE" = "1" ]' {
  set-window-option -g window-active-style "fg=#c38e69,bg=#2a1a4a"
  set-window-option -g window-style "fg=#c38e69,bg=#0a041f"
}

# Optional statusbar
if-shell '[ "$TINTED_TMUX_OPTION_STATUSBAR" = "1" ]' {
  set-option -g status "on"
  set-option -g status-justify "left"
  set-option -g status-left "#[fg=#c38e69,bg=#4b3639] #S #[fg=#4b3639,bg=#0a041f,nobold,noitalics,nounderscore]"
  set-option -g status-left-length "80"
  set-option -g status-left-style none
  set-option -g status-right "#[fg=#100b22,bg=#0a041f nobold, nounderscore, noitalics]#[fg=#876251,bg=#100b22] %Y-%m-%d  %H:%M #[fg=#c38e69,bg=#100b22,nobold,noitalics,nounderscore]#[fg=#0a041f,bg=#c38e69] #h "
  set-option -g status-right-length "80"
  set-option -g status-right-style none
  set-window-option -g window-status-current-format "#[fg=#0a041f,bg=#79daed,nobold,noitalics,nounderscore]#[fg=#100b22,bg=#79daed] #I #[fg=#100b22,bg=#79daed,bold] #W#{?window_zoomed_flag,*Z,}} #[fg=#79daed,bg=#0a041f,nobold,noitalics,nounderscore]"
  set-window-option -g window-status-format "#[fg=#0a041f,bg=#100b22,noitalics]#[fg=#ffba81,bg=#100b22] #I #[fg=#ffba81,bg=#100b22] #W#{?window_zoomed_flag,*Z,}} #[fg=#100b22,bg=#0a041f,noitalics]"
  set-window-option -g window-status-separator ""
}

# vim: set ft=tmux tw=0:
