# Base24 Dark Plus
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Tinted Theming: (https://github.com/tinted-theming)

# Global base24 color variables
%hidden base00="#0e0e0e"
%hidden base01="#000000"
%hidden base02="#666666"
%hidden base03="#858585"
%hidden base04="#a5a5a5"
%hidden base05="#c5c5c5"
%hidden base06="#e5e5e5"
%hidden base07="#e5e5e5"
%hidden base08="#cd3131"
%hidden base09="#e5e510"
%hidden base0A="#3b8eea"
%hidden base0B="#0dbc79"
%hidden base0C="#11a8cd"
%hidden base0D="#2472c8"
%hidden base0E="#bc3fbc"
%hidden base10="#444444"
%hidden base11="#222222"
%hidden base12="#f14c4c"
%hidden base13="#f5f543"
%hidden base14="#23d18b"
%hidden base15="#29b8db"
%hidden base16="#3b8eea"
%hidden base17="#d670d6"

# default statusbar colors
set-option -g status-style "fg=#a5a5a5,bg=#000000"

# default window title colors
set-window-option -g window-status-style "fg=#a5a5a5,bg=#000000"

# active window title colors
set-window-option -g window-status-current-style "fg=#f5f543,bg=#000000"

# pane border
set-option -g pane-border-style "fg=#000000"
set-option -g pane-active-border-style "fg=#a5a5a5"

# message text
set-option -g message-style "fg=#e5e5e5,bg=#666666"

# pane number display
set-option -g display-panes-active-colour "#a5a5a5"
set-option -g display-panes-colour "#000000"

# clock
set-window-option -g clock-mode-colour "#2472c8"

# copy mode highlight
set-window-option -g mode-style "fg=#a5a5a5,bg=#666666"

# bell
set-window-option -g window-status-bell-style "fg=#0e0e0e,bg=#cd3131"

# style for window titles with activity
set-window-option -g window-status-activity-style "fg=#c5c5c5,bg=#000000"

# style for command messages
set-option -g message-command-style "fg=#e5e5e5,bg=#666666"

# Optional active/inactive pane state
if-shell '[ "$TINTED_TMUX_OPTION_ACTIVE" = "1" ]' {
  set-window-option -g window-active-style "fg=#c5c5c5,bg=#0e0e0e"
  set-window-option -g window-style "fg=#c5c5c5,bg=#000000"
}

# Optional statusbar
if-shell '[ "$TINTED_TMUX_OPTION_STATUSBAR" = "1" ]' {
  set-option -g status "on"
  set-option -g status-justify "left"
  set-option -g status-left "#[fg=#c5c5c5,bg=#858585] #S #[fg=#858585,bg=#000000,nobold,noitalics,nounderscore]"
  set-option -g status-left-length "80"
  set-option -g status-left-style none
  set-option -g status-right "#[fg=#666666,bg=#000000 nobold, nounderscore, noitalics]#[fg=#a5a5a5,bg=#666666] %Y-%m-%d  %H:%M #[fg=#c5c5c5,bg=#666666,nobold,noitalics,nounderscore]#[fg=#000000,bg=#c5c5c5] #h "
  set-option -g status-right-length "80"
  set-option -g status-right-style none
  set-window-option -g window-status-current-format "#[fg=#000000,bg=#3b8eea,nobold,noitalics,nounderscore]#[fg=#666666,bg=#3b8eea] #I #[fg=#666666,bg=#3b8eea,bold] #W#{?window_zoomed_flag,*Z,}} #[fg=#3b8eea,bg=#000000,nobold,noitalics,nounderscore]"
  set-window-option -g window-status-format "#[fg=#000000,bg=#666666,noitalics]#[fg=#e5e5e5,bg=#666666] #I #[fg=#e5e5e5,bg=#666666] #W#{?window_zoomed_flag,*Z,}} #[fg=#666666,bg=#000000,noitalics]"
  set-window-option -g window-status-separator ""
}

# vim: set ft=tmux tw=0:
