# Base24 Bluloco Light
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Tinted Theming: (https://github.com/tinted-theming)

# Global base24 color variables
%hidden base00="#f7f7f7"
%hidden base01="#cbccd4"
%hidden base02="#dddee8"
%hidden base03="#a6a7ae"
%hidden base04="#6f6f74"
%hidden base05="#38383a"
%hidden base06="#000000"
%hidden base07="#1c1d21"
%hidden base08="#c80d41"
%hidden base09="#d44d16"
%hidden base0A="#1085d9"
%hidden base0B="#208839"
%hidden base0C="#1e4d7a"
%hidden base0D="#1d44dd"
%hidden base0E="#6d1bed"
%hidden base10="#93949a"
%hidden base11="#494a4d"
%hidden base12="#fb496d"
%hidden base13="#b79326"
%hidden base14="#34b253"
%hidden base15="#5a7fac"
%hidden base16="#1085d9"
%hidden base17="#c00cb2"

# default statusbar colors
set-option -g status-style "fg=#6f6f74,bg=#cbccd4"

# default window title colors
set-window-option -g window-status-style "fg=#6f6f74,bg=#cbccd4"

# active window title colors
set-window-option -g window-status-current-style "fg=#b79326,bg=#cbccd4"

# pane border
set-option -g pane-border-style "fg=#cbccd4"
set-option -g pane-active-border-style "fg=#6f6f74"

# message text
set-option -g message-style "fg=#000000,bg=#dddee8"

# pane number display
set-option -g display-panes-active-colour "#6f6f74"
set-option -g display-panes-colour "#cbccd4"

# clock
set-window-option -g clock-mode-colour "#1d44dd"

# copy mode highlight
set-window-option -g mode-style "fg=#6f6f74,bg=#dddee8"

# bell
set-window-option -g window-status-bell-style "fg=#f7f7f7,bg=#c80d41"

# style for window titles with activity
set-window-option -g window-status-activity-style "fg=#38383a,bg=#cbccd4"

# style for command messages
set-option -g message-command-style "fg=#000000,bg=#dddee8"

# Optional active/inactive pane state
if-shell '[ "$TINTED_TMUX_OPTION_ACTIVE" = "1" ]' {
  set-window-option -g window-active-style "fg=#38383a,bg=#f7f7f7"
  set-window-option -g window-style "fg=#38383a,bg=#cbccd4"
}

# Optional statusbar
if-shell '[ "$TINTED_TMUX_OPTION_STATUSBAR" = "1" ]' {
  set-option -g status "on"
  set-option -g status-justify "left"
  set-option -g status-left "#[fg=#38383a,bg=#a6a7ae] #S #[fg=#a6a7ae,bg=#cbccd4,nobold,noitalics,nounderscore]"
  set-option -g status-left-length "80"
  set-option -g status-left-style none
  set-option -g status-right "#[fg=#dddee8,bg=#cbccd4 nobold, nounderscore, noitalics]#[fg=#6f6f74,bg=#dddee8] %Y-%m-%d  %H:%M #[fg=#38383a,bg=#dddee8,nobold,noitalics,nounderscore]#[fg=#cbccd4,bg=#38383a] #h "
  set-option -g status-right-length "80"
  set-option -g status-right-style none
  set-window-option -g window-status-current-format "#[fg=#cbccd4,bg=#1085d9,nobold,noitalics,nounderscore]#[fg=#dddee8,bg=#1085d9] #I #[fg=#dddee8,bg=#1085d9,bold] #W#{?window_zoomed_flag,*Z,}} #[fg=#1085d9,bg=#cbccd4,nobold,noitalics,nounderscore]"
  set-window-option -g window-status-format "#[fg=#cbccd4,bg=#dddee8,noitalics]#[fg=#000000,bg=#dddee8] #I #[fg=#000000,bg=#dddee8] #W#{?window_zoomed_flag,*Z,}} #[fg=#dddee8,bg=#cbccd4,noitalics]"
  set-window-option -g window-status-separator ""
}

# vim: set ft=tmux tw=0:
