# Base16 Tango
# Scheme author: @Schnouki, based on the Tango Desktop Project
# Template author: Tinted Theming: (https://github.com/tinted-theming)

# Global base16 color variables
%hidden base00="#2e3436"
%hidden base01="#8ae234"
%hidden base02="#fce94f"
%hidden base03="#555753"
%hidden base04="#729fcf"
%hidden base05="#d3d7cf"
%hidden base06="#ad7fa8"
%hidden base07="#eeeeec"
%hidden base08="#cc0000"
%hidden base09="#ef2929"
%hidden base0A="#c4a000"
%hidden base0B="#4e9a06"
%hidden base0C="#06989a"
%hidden base0D="#3465a4"
%hidden base0E="#75507b"
%hidden base0F="#34e2e2"

# default statusbar colors
set-option -g status-style "fg=#729fcf,bg=#8ae234"

# default window title colors
set-window-option -g window-status-style "fg=#729fcf,bg=#8ae234"

# active window title colors
set-window-option -g window-status-current-style "fg=#c4a000,bg=#8ae234"

# pane border
set-option -g pane-border-style "fg=#8ae234"
set-option -g pane-active-border-style "fg=#729fcf"

# message text
set-option -g message-style "fg=#ad7fa8,bg=#fce94f"

# pane number display
set-option -g display-panes-active-colour "#729fcf"
set-option -g display-panes-colour "#8ae234"

# clock
set-window-option -g clock-mode-colour "#3465a4"

# copy mode highlight
set-window-option -g mode-style "fg=#729fcf,bg=#fce94f"

# bell
set-window-option -g window-status-bell-style "fg=#2e3436,bg=#cc0000"

# style for window titles with activity
set-window-option -g window-status-activity-style "fg=#d3d7cf,bg=#8ae234"

# style for command messages
set-option -g message-command-style "fg=#ad7fa8,bg=#fce94f"

# Optional active/inactive pane state
# BASE16_TMUX_OPTION_ACTIVE is a legacy variable
if-shell '[ "$TINTED_TMUX_OPTION_ACTIVE" = "1" ] || [ "$BASE16_TMUX_OPTION_ACTIVE" = "1" ]' {
  set-window-option -g window-active-style "fg=#d3d7cf,bg=#2e3436"
  set-window-option -g window-style "fg=#d3d7cf,bg=#8ae234"
}

# Optional statusbar
# BASE16_TMUX_OPTION_STATUSBAR is a legacy variable
if-shell '[ "$TINTED_TMUX_OPTION_STATUSBAR" = "1" ] || [ "$BASE16_TMUX_OPTION_STATUSBAR" = "1" ]' {
  set-option -g status "on"
  set-option -g status-justify "left"
  set-option -g status-left "#[fg=#d3d7cf,bg=#555753] #S #[fg=#555753,bg=#8ae234,nobold,noitalics,nounderscore]"
  set-option -g status-left-length "80"
  set-option -g status-left-style none
  set-option -g status-right "#[fg=#fce94f,bg=#8ae234 nobold, nounderscore, noitalics]#[fg=#729fcf,bg=#fce94f] %Y-%m-%d  %H:%M #[fg=#d3d7cf,bg=#fce94f,nobold,noitalics,nounderscore]#[fg=#8ae234,bg=#d3d7cf] #h "
  set-option -g status-right-length "80"
  set-option -g status-right-style none
  set-window-option -g window-status-current-format "#[fg=#8ae234,bg=#c4a000,nobold,noitalics,nounderscore]#[fg=#fce94f,bg=#c4a000] #I #[fg=#fce94f,bg=#c4a000,bold] #W#{?window_zoomed_flag,*Z,} #[fg=#c4a000,bg=#8ae234,nobold,noitalics,nounderscore]"
  set-window-option -g window-status-format "#[fg=#8ae234,bg=#fce94f,noitalics]#[fg=#ad7fa8,bg=#fce94f] #I #[fg=#ad7fa8,bg=#fce94f] #W#{?window_zoomed_flag,*Z,} #[fg=#fce94f,bg=#8ae234,noitalics]"
  set-window-option -g window-status-separator ""
}

# vim: set ft=tmux tw=0:
