# Base24 Atelier Sulphurpool
# Scheme author: FredHappyface (https://github.com/fredHappyface)
# Template author: Tinted Theming: (https://github.com/tinted-theming)

# Global base24 color variables
%hidden base00="#202746"
%hidden base01="#202746"
%hidden base02="#6b7394"
%hidden base03="#767d9c"
%hidden base04="#8188a4"
%hidden base05="#8c92ac"
%hidden base06="#979db4"
%hidden base07="#f5f7ff"
%hidden base08="#c94922"
%hidden base09="#c08b30"
%hidden base0A="#898ea4"
%hidden base0B="#ac9739"
%hidden base0C="#22a2c9"
%hidden base0D="#3d8fd1"
%hidden base0E="#6679cc"
%hidden base10="#474c62"
%hidden base11="#232631"
%hidden base12="#c76b29"
%hidden base13="#5e6687"
%hidden base14="#293256"
%hidden base15="#9c637a"
%hidden base16="#898ea4"
%hidden base17="#dfe2f1"

# default statusbar colors
set-option -g status-style "fg=#8188a4,bg=#202746"

# default window title colors
set-window-option -g window-status-style "fg=#8188a4,bg=#202746"

# active window title colors
set-window-option -g window-status-current-style "fg=#5e6687,bg=#202746"

# pane border
set-option -g pane-border-style "fg=#202746"
set-option -g pane-active-border-style "fg=#8188a4"

# message text
set-option -g message-style "fg=#979db4,bg=#6b7394"

# pane number display
set-option -g display-panes-active-colour "#8188a4"
set-option -g display-panes-colour "#202746"

# clock
set-window-option -g clock-mode-colour "#3d8fd1"

# copy mode highlight
set-window-option -g mode-style "fg=#8188a4,bg=#6b7394"

# bell
set-window-option -g window-status-bell-style "fg=#202746,bg=#c94922"

# style for window titles with activity
set-window-option -g window-status-activity-style "fg=#8c92ac,bg=#202746"

# style for command messages
set-option -g message-command-style "fg=#979db4,bg=#6b7394"

# Optional active/inactive pane state
if-shell '[ "$TINTED_TMUX_OPTION_ACTIVE" = "1" ]' {
  set-window-option -g window-active-style "fg=#8c92ac,bg=#202746"
  set-window-option -g window-style "fg=#8c92ac,bg=#202746"
}

# Optional statusbar
if-shell '[ "$TINTED_TMUX_OPTION_STATUSBAR" = "1" ]' {
  set-option -g status "on"
  set-option -g status-justify "left"
  set-option -g status-left "#[fg=#8c92ac,bg=#767d9c] #S #[fg=#767d9c,bg=#202746,nobold,noitalics,nounderscore]"
  set-option -g status-left-length "80"
  set-option -g status-left-style none
  set-option -g status-right "#[fg=#6b7394,bg=#202746 nobold, nounderscore, noitalics]#[fg=#8188a4,bg=#6b7394] %Y-%m-%d  %H:%M #[fg=#8c92ac,bg=#6b7394,nobold,noitalics,nounderscore]#[fg=#202746,bg=#8c92ac] #h "
  set-option -g status-right-length "80"
  set-option -g status-right-style none
  set-window-option -g window-status-current-format "#[fg=#202746,bg=#898ea4,nobold,noitalics,nounderscore]#[fg=#6b7394,bg=#898ea4] #I #[fg=#6b7394,bg=#898ea4,bold] #W#{?window_zoomed_flag,*Z,}} #[fg=#898ea4,bg=#202746,nobold,noitalics,nounderscore]"
  set-window-option -g window-status-format "#[fg=#202746,bg=#6b7394,noitalics]#[fg=#979db4,bg=#6b7394] #I #[fg=#979db4,bg=#6b7394] #W#{?window_zoomed_flag,*Z,}} #[fg=#6b7394,bg=#202746,noitalics]"
  set-window-option -g window-status-separator ""
}

# vim: set ft=tmux tw=0:
